<a href="https://colab.research.google.com/github/himabindu-2005/pandaas./blob/main/Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd
data=pd.read_csv('/content/business-financial-data-march-2024 (2).zip')
data

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,BDCQ.SF1AA2CA,2016.06,1116.386,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
1,BDCQ.SF1AA2CA,2016.09,1070.874,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
2,BDCQ.SF1AA2CA,2016.12,1054.408,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
3,BDCQ.SF1AA2CA,2017.03,1010.665,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
4,BDCQ.SF1AA2CA,2017.06,1233.700,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 2),Sales (operating income),Forestry and Logging,Current prices,Unadjusted,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7630,BDCQ.SF8RSCA,2023.03,663.630,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
7631,BDCQ.SF8RSCA,2023.06,617.507,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
7632,BDCQ.SF8RSCA,2023.09,673.068,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
7633,BDCQ.SF8RSCA,2023.12,511.098,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN
7634,BDCQ.SF8RSCA,2024.03,631.229,NaN,F,Dollars,6,Business Data Collection - BDC,Industry by financial variable (NZSIOC Level 1),Operating profit,"Arts, Recreation and Other Services",Current,Unadjusted,NaN

In [ ]:
dat=pd.read_csv()